# Generated by Django 5.2.5 on 2026-09-21 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='شرح هزینه')),
                ('category', models.CharField(choices=[('حقوق و دستمزد', 'حقوق و دستمزد'), ('اجاره و قبوض', 'اجاره و قبوض'), ('تجهیزات', 'تجهیزات'), ('نگهداری', 'نگهداری'), ('بازاریابی', 'بازاریابی'), ('سایر', 'سایر')], max_length=30, verbose_name='دسته\u200cبندی')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='فروشنده / مسئول')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ (تومان)')),
                ('date', models.DateField(verbose_name='تاریخ هزینه')),
                ('status', models.CharField(choices=[('پرداخت\u200cشده', 'پرداخت\u200cشده'), ('در انتظار پرداخت', 'در انتظار پرداخت')], default='پرداخت\u200cشده', max_length=20, verbose_name='وضعیت پرداخت')),
                ('method', models.CharField(blank=True, max_length=30, verbose_name='روش پرداخت')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='شماره فاکتور')),
                ('operator', models.CharField(blank=True, max_length=60, verbose_name='ثبت\u200cکننده')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ (تومان)')),
                ('plan_label', models.CharField(blank=True, max_length=60, verbose_name='نوع پرداخت')),
                ('method', models.CharField(choices=[('کارتخوان', 'کارتخوان'), ('کارت به کارت', 'کارت به کارت'), ('نقدی', 'نقدی'), ('درگاه آنلاین', 'درگاه آنلاین')], default='کارتخوان', max_length=30, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('موفق', 'موفق'), ('در انتظار', 'در انتظار'), ('ناموفق', 'ناموفق')], default='موفق', max_length=20, verbose_name='وضعیت')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='شماره پیگیری')),
                ('operator', models.CharField(blank=True, max_length=60, verbose_name='ثبت\u200cکننده')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member', verbose_name='عضو')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.subscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
