# Generated by Django 5.2.5 on 2026-09-28 09:21

import uuid

from django.db import migrations, models


def make_references_unique(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    db_alias = schema_editor.connection.alias
    payments = Payment.objects.using(db_alias)
    used_references = set()
    for payment in payments.order_by('pk').values('pk', 'reference').iterator():
        reference = payment['reference']
        if not reference or reference in used_references:
            reference = f'TRX{uuid.uuid4().hex}'
            while reference in used_references or payments.filter(reference=reference).exists():
                reference = f'TRX{uuid.uuid4().hex}'
            payments.filter(pk=payment['pk']).update(reference=reference)
        used_references.add(reference)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_references_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='شماره پیگیری'),
        ),
    ]
