# Generated by Django 5.2.5 on 2026-10-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_alter_gymsubscription_options_and_more'),
        ('payments', '0003_protect_payment_member_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
