# Generated by Django 5.2.5 on 2026-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gymsettings_gym_alter_gymsubscription_gym_and_more'),
        ('payments', '0004_expense_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
