# Generated by Django 5.2.5 on 2026-09-21 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
            ],
            options={
                'verbose_name': 'مربی',
                'verbose_name_plural': 'مربی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام کلاس')),
                ('days', models.CharField(blank=True, help_text='کلیدهای روز جدا شده با فاصله، مثل: saturday monday', max_length=120, verbose_name='روزهای برگزاری')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.coach', verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ClassPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(choices=[(12, '۱۲ جلسه'), (36, '۳۶ جلسه'), (120, '۱۲۰ جلسه')], verbose_name='تعداد جلسات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='classes.gymclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'پلن کلاس',
                'verbose_name_plural': 'پلن\u200cهای کلاس',
                'unique_together': {('gym_class', 'sessions')},
            },
        ),
    ]
