# Generated by Django 5.2.5 on 2026-10-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('gyms', '0004_gym_alter_gymsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
