# Generated by Django 5.2.5 on 2026-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_coach_gym_gymclass_gym'),
        ('gyms', '0006_alter_gymsettings_gym_alter_gymsubscription_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
