# Generated by Django 5.2.5 on 2026-10-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_and_coach_roles'),
        ('gyms', '0004_gym_alter_gymsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
