# Generated by Django 5.2.5 on 2026-09-21 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='باشگاه ورزشی المپیک', max_length=120, verbose_name='نام باشگاه')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.FileField(blank=True, upload_to='gym/', verbose_name='لوگو')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='رنگ اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات باشگاه',
                'verbose_name_plural': 'تنظیمات باشگاه',
            },
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(choices=[(12, '۱۲ جلسه'), (36, '۳۶ جلسه'), (120, '۱۲۰ جلسه')], default=12, verbose_name='دوره')),
                ('price', models.DecimalField(decimal_places=0, default=2500000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ دوره (تومان)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('در انتظار پرداخت', 'در انتظار پرداخت')], default='فعال', max_length=30, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'اشتراک باشگاه',
                'verbose_name_plural': 'اشتراک\u200cهای باشگاه',
                'ordering': ('-end_date',),
            },
        ),
    ]
