# Generated by Django 5.2.5 on 2026-09-28 10:07

import django.db.models.deletion
import django.utils.timezone
import gyms.models
from django.conf import settings
from django.db import migrations, models


def normalize_pending_status(apps, schema_editor):
    GymSubscription = apps.get_model('gyms', 'GymSubscription')
    GymSubscription.objects.using(schema_editor.connection.alias).filter(
        status='در انتظار پرداخت'
    ).update(status='در انتظار بررسی')


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_singleton_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsubscription',
            name='invoice_image',
            field=models.ImageField(blank=True, upload_to='gym_subscriptions/invoices/', validators=[gyms.models.validate_invoice_image], verbose_name='تصویر رسید پرداخت'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_subscription_reviews', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.RunPython(normalize_pending_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gymsubscription',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('در انتظار بررسی', 'در انتظار بررسی'), ('رد شده', 'رد شده'), ('منقضی', 'منقضی')], default='در انتظار بررسی', max_length=30, verbose_name='وضعیت'),
        ),
    ]
