# Generated by Django 5.2.5 on 2026-10-01 07:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gyms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gymsubscription_invoice_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام باشگاه')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='شناسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'باشگاه',
                'verbose_name_plural': 'باشگاه\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='gymsubscription',
            options={'ordering': ('-end_date', '-pk'), 'verbose_name': 'اشتراک باشگاه', 'verbose_name_plural': 'اشتراک\u200cهای باشگاه'},
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('منقضی', 'منقضی')], default='فعال', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='gym',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.CreateModel(
            name='GymSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(choices=[(12, '۱۲ جلسه'), (36, '۳۶ جلسه'), (120, '۱۲۰ جلسه')], verbose_name='دوره')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ دوره (تومان)')),
                ('invoice_image', models.ImageField(upload_to='gym_subscriptions/invoices/', validators=[gyms.models.validate_invoice_image], verbose_name='تصویر رسید پرداخت')),
                ('status', models.CharField(choices=[('در انتظار بررسی', 'در انتظار بررسی'), ('تأیید شده', 'تأیید شده'), ('رد شده', 'رد شده')], default='در انتظار بررسی', max_length=30, verbose_name='وضعیت')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ درخواست')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='gyms.gym', verbose_name='باشگاه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_subscription_reviews', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='gyms.gymsubscription', verbose_name='اشتراک ایجادشده')),
            ],
            options={
                'verbose_name': 'درخواست اشتراک SaaS',
                'verbose_name_plural': 'درخواست\u200cهای اشتراک SaaS',
                'ordering': ('-submitted_at', '-pk'),
            },
        ),
    ]
