# Generated by Django 5.2.5 on 2026-10-01 16:09

import django.db.models.deletion
import gyms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_backfill_gym_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsettings',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymsubscriptionrequest',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymsubscriptionrequest',
            name='invoice_image',
            field=models.ImageField(blank=True, upload_to='gym_subscriptions/invoices/', validators=[gyms.models.validate_invoice_image], verbose_name='تصویر رسید پرداخت'),
        ),
    ]
