# Generated by Django 5.2.5 on 2026-09-21 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=10, verbose_name='جنسیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='classes.coach', verbose_name='مربی')),
                ('gym_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='classes.gymclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد جلسات')),
                ('remaining_sessions', models.PositiveIntegerField(default=0, verbose_name='جلسات باقی\u200cمانده')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی'), ('pending', 'در انتظار')], default='active', max_length=20, verbose_name='وضعیت')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member', verbose_name='عضو')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='classes.classplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ('-start_date',),
            },
        ),
    ]
