# Generated by Django 5.2.5 on 2026-09-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال\u200cسازی ارسال پیامک')),
                ('expiry_sms', models.BooleanField(default=True, verbose_name='پیامک انقضای اشتراک')),
                ('payment_sms', models.BooleanField(default=True, verbose_name='پیامک پرداخت')),
                ('registration_sms', models.BooleanField(default=True, verbose_name='پیامک ثبت\u200cنام')),
                ('reminder_sms', models.BooleanField(default=True, verbose_name='پیامک یادآوری کلاس')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=120, verbose_name='نوع پیام')),
                ('body', models.TextField(verbose_name='متن اعلانیه')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('classes', models.ManyToManyField(related_name='announcements', to='classes.gymclass', verbose_name='کلاس\u200cهای هدف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'اعلانیه',
                'verbose_name_plural': 'اعلانیه\u200cها',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='MemberNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_reminder', models.BooleanField(default=True, verbose_name='یادآوری کلاس')),
                ('subscription_expiry', models.BooleanField(default=True, verbose_name='انقضای اشتراک')),
                ('payment', models.BooleanField(default=True, verbose_name='پرداخت')),
                ('registration', models.BooleanField(default=True, verbose_name='ثبت\u200cنام')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='members.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک عضو',
                'verbose_name_plural': 'تنظیمات پیامک اعضا',
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('یادآوری کلاس', 'یادآوری کلاس'), ('انقضای اشتراک', 'انقضای اشتراک'), ('پرداخت', 'پرداخت'), ('ثبت\u200cنام', 'ثبت\u200cنام'), ('اعلانیه', 'اعلانیه')], max_length=30, verbose_name='نوع پیام')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('ارسال شد', 'ارسال شد'), ('در انتظار', 'در انتظار'), ('ناموفق', 'ناموفق')], default='ارسال شد', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='members.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
