# Generated by Django 5.2.5 on 2026-10-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_alter_gymsubscription_options_and_more'),
        ('notifications', '0002_alter_smsmessage_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='gym',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
