# Generated by Django 5.2.5 on 2026-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gymsettings_gym_alter_gymsubscription_gym_and_more'),
        ('notifications', '0003_announcement_gym_smsmessage_gym_smssettings_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='gyms.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='gyms.gym', verbose_name='باشگاه'),
        ),
    ]
